services:
  app:
    container_name: tinystatus
    image: tinystatus
    build:
      context: .
      dockerfile: Dockerfile
    # ports:
    #   - "8080:8080"
    networks:
      - test-network
    environment:
      - MONITOR_CONTINOUSLY=True
      - CHECK_INTERVAL=30
      - MAX_HISTORY_ENTRIES=100
      - LOG_LEVEL=INFO
      - CHECKS_FILE=checks.yaml
      - INCIDENTS_FILE=incidents.md
      - TEMPLATE_FILE=index.html.theme
      - HISTORY_TEMPLATE_FILE=history.html.theme
      - STATUS_HISTORY_FILE=history.json
      - HTML_OUTPUT_DIRECTORY=templates

  nginx:
    image: nginx
    # restart: always
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - test-network
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    hostname: nginx
    depends_on:
      - app

networks:
  test-network: 
   driver: bridge
